name: dmxCanvas GitHub Actions CI Build

on: ["push", "pull_request"]

jobs:
  linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v4

      - name: Compile
        run: |
          qmake dmxCanvas.pro
          make
          make install DESTDIR=AppDir
          make clean

      - name: Create Debian Package
        working-directory: build
        run: |
          mkdir -p dmxCanvas-amd64/usr/local/bin
          cp ../src/dmxCanvas dmxCanvas-amd64/usr/local/bin
          dpkg-deb --build --root-owner-group dmxCanvas-amd64

      - name: Upload Debian Package
        uses: actions/upload-artifact@v4
        with:
          name: dmxCanvas-amd64.deb
          path: build/dmxCanvas-amd64.deb

      - name: Create AppImage
        uses: AppImageCrafters/build-appimage-action@master

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: dmxCanvas-amd64.AppImage
          path: build/dmxCanvas*.AppImage

  windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v2

      - name: Compile
        run: |
             qmake dmxCanvas.pro
             nmake release
             nmake clean
