name: dmxCanvas GitHub Actions CI Build
on: [ push, pull_request ]
env:
  QT_VERSION: "6.8.0"

jobs:
  linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}

      - name: Compile
        run: |
          qmake dmxCanvas.pro
          make
          make install INSTALL_ROOT=AppDir
          make clean

      - name: Create AppImage
        run: |
          sudo add-apt-repository universe
          sudo apt install libfuse2
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
          chmod +x linuxdeploy*.AppImage
          ./linuxdeploy-x86_64.AppImage --appdir AppDir -e dmxCanvas --plugin qt -d ../build/dmxCanvas.desktop -i ../src/resources/icon.png --output appimage

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: dmxCanvas.AppImage
          path: src/dmxCanvas*.AppImage

  windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          spectre: true

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        #with:
        #  version: ${{ env.QT_VERSION }}

      - name: Install NSIS
        run: |
             Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
             scoop bucket add extras
             scoop install nsis

      - name: Compile
        run: |
             qmake dmxCanvas.pro
             nmake
             nmake clean

      - name: Deploy
        run: |
             mkdir bin
             move release/dmxCanvas.exe bin
             windeployqt bin/dmxCanvas.exe -qmldir="assets\\qml" --compiler-runtime
             mkdir dmxCanvas
             move bin dmxCanvas
             cd \deploy\windows\nsis

      - name: Create installer
        run: |
             move dmxCanvas \deploy\windows\nsis\
             cd \deploy\windows\nsis
             makensis /X"SetCompressor /FINAL lzma" setup.nsi
             ren *.exe dmxCanvas.exe

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: dmxCanvas.exe
          path: deploy/windows/nsis/dmxCanvas.exe
