name: dmxCanvas GitHub Actions CI Build

on: ["push", "pull_request"]

jobs:
  linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v4

      - name: Compile
        run: |
          qmake dmxCanvas.pro
          make
          make install DESTDIR=AppDir
          make clean

      - name: Create Debian Package
        working-directory: build
        run: |
          mkdir -p dmxCanvas-amd64/usr/local/bin
          cp ../src/dmxCanvas dmxCanvas-amd64/usr/local/bin
          dpkg-deb --build --root-owner-group dmxCanvas-amd64

      - name: Upload Debian Package
        uses: actions/upload-artifact@v4
        with:
          name: dmxCanvas-amd64.deb
          path: build/dmxCanvas-amd64.deb

      - name: Download Qt Library
        run: sudo apt install libqt6widgets6t64

      - name: Create AppImage
        uses: AppImageCrafters/build-appimage-action@master
        with:
          recipe: build/AppImageBuilder.yml

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: dmxCanvas-amd64.AppImage
          path: build/dmxCanvas*.AppImage

  windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          spectre: true

      - name: Install Qt
        uses: jurplel/install-qt-action@v2

      - name: Install NSIS
        run: |
             Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
             scoop bucket add extras
             scoop install nsis

      - name: Compile
        run: |
             qmake dmxCanvas.pro
             nmake
             nmake clean

      - name: Deploy
        run: |
             mkdir bin
             move release/dmxCanvas.exe bin
             windeployqt bin/dmxCanvas.exe -qmldir="assets\\qml" --compiler-runtime
             mkdir dmxCanvas
             move bin "dmxCanvas"

      - name: Make installer
        run: |
             move bin/dmxCanvas deploy\windows\nsis\
             cd deploy\windows\nsis
             makensis /X"SetCompressor /FINAL lzma" setup.nsi
             ren *.exe dmxCanvas.exe

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: dmxCanvas.exe
          path: deploy/windows/nsis/dmxCanvas.exe
