name: dmxCanvas GitHub Actions CI Build

on: ["push", "pull_request"]

jobs:
  linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v4

      - name: Create Makefile
        run: qmake dmxCanvas.pro

      - name: Run Makefile
        run: make

      - name: Create Debian Package
        run: |
          cd ../build/
          mkdir -p dmxCanvas-amd64/usr/local/bin
          cp ../src/dmxCanvas dmxCanvas-amd64/usr/local/bin
          dpkg-deb --build --root-owner-group dmxCanvas-amd64

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dmxCanvas-amd64.deb
          path: build/dmxCanvas-amd64.deb
