name: dmxCanvas GitHub Actions CI Build

on: ["push", "pull_request"]

jobs:
  linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v4

      - name: Create Makefile
        run: qmake dmxCanvas.pro

      - name: Run Makefile
        run: make

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linux
          path: |
            dmxCanvas*.AppImage
            install/linux/*.deb
